name: The best workflow

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

env:
  MIRROR_URL: EpitechPGEPromo2029/B-DOP-200-TLS-2-1-chocolatine-pavel.de-wavrechin
  EXECUTABLES: mysh

jobs:

  coding_style:

    if: ${{ github.repository != vars.MIRROR_REPO }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest

    steps:
      - name: check_coding_style
        uses: actions/checkout@v4
      
      - name: run and analyse codebase
        run: |
          check.sh $(pwd) $(pwd)

          while read -r line; do
            file=$(echo "$line" | awk -F: '{print $1}' | cut -c3-)
            line_number=$(echo "$line" | awk -F: '{print $2}')
            severity=$(echo "$line" | awk -F: '{print $3}' | awk '{print $1}')
            error_type=$(echo "$line" | awk -F: '{print $4}')

            if [ "$severity" = "INFO" ]; then
              echo "::error file=$file,line=$line_number::INFO coding style error: $error_type"
            elif [ "$severity" = "MINOR" ]; then
              echo "::error file=$file,line=$line_number::MINOR coding style error: $file#L$line_number $error_type"
            elif [ "$severity" = "MAJOR" ]; then
              echo "::error file=$file,line=$line_number::MAJOR coding style error: $file#L$line_number $error_type"
            fi
          done < coding-style-reports.log

