name: The best workflow

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

env:
  MIRROR_REPO: EpitechPGEPromo2029/B-DOP-200-TLS-2-1-chocolatine-pavel.de-wavrechin
  EXECUTABLES: ${{ secrets.EXECUTABLES }}

jobs:
  validate-and-mirror:
    if: ${{ vars.MIRROR_REPO == 'b' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check if repo should mirror
        id: repo-check
        run: echo "BONJOUR"
